name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]  # Update to the desired Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change to the frontend directory
        run: cd frontend

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build --if-present

      - name: Commit and push
        run: |
          git add build/*
          git commit -m "Build update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
