name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [20.x]  # Update to the desired Node.js version

    steps:
      - name: Checking out code
        uses: actions/checkout@v3
        
      - name: Setting up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Starting Build
        run: yarn run build --if-present

      #- name: Commit and push
      #  run: |
      #    git config user.name "P0W"
      #    git config user.email "powprashant@gmail.com"
      #    git add build/* -f
      #    git commit -m "Build update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      #    git push

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Created new build'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: 'build/* --force'
          cwd: './frontend'
